language: csharp
solution: LibuvSharp.sln

install:
  - nuget restore LibuvSharp.sln
  - mkdir -p bin/Debug
  - make
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory bin/Debug

script:
  - xbuild LibuvSharp.sln
  - cd bin/Debug
  - LD_LIBRARY_PATH=$(HOME)/libuv/.libs/:$LD_LIBRARY_PATH mono --debug xunit.runners.1.9.2/tools/xunit.console.clr4.exe LibuvSharp.Tests.dll
