# Travis-CI Build for libgit2sharp
# see travis-ci.org for details

language: c

# Make sure CMake is installed
install:
- sudo apt-get install mono-gmcs mono-devel

# Run the Build script
script:
 - make

# Run Tests
after_script:
 - xbuild LibuvSharp/LibuvSharp.csproj
